# Generated by Django 3.0.4 on 2020-05-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Blog',
        ),
    ]
