# Generated by Django 3.0.4 on 2020-05-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0002_auto_20200518_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='blog_desc',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
    ]
