# Generated by Django 3.0.4 on 2020-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0004_blog_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
