# Generated by Django 3.0.4 on 2020-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0005_auto_20200520_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
    ]
