# Generated by Django 3.0.4 on 2020-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0007_auto_20200520_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover',
        ),
        migrations.AddField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
