# Generated by Django 3.0.4 on 2020-05-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0009_appeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsors_title', models.CharField(max_length=100)),
                ('sponsors_desc', models.TextField(max_length=1000)),
                ('sponsors_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
