# Generated by Django 3.0.4 on 2020-05-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0010_sponsor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appeals',
            new_name='Appeal',
        ),
    ]
