# Generated by Django 3.0.4 on 2020-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0012_auto_20200528_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_desc', models.TextField(max_length=1000)),
                ('event_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
