# Generated by Django 3.0.4 on 2020-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0013_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desc', models.TextField(max_length=200)),
                ('image_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
